#!/usr/bin/env bash
# This script displays username, UID, and home directory from /etc/passwd
# shellcheck disable=SC2034

while IFS=':' read -r username _ uid _ _ _ home _
do
  echo "Username: $username"
  echo "UID: $uid"
  echo "Home Directory: $home"
done < /etc/passwd
