#!/usr/bin/env bash
# This script groups Apache log entries by IP and HTTP status code
# shellcheck disable=SC2034

awk '{ print $1, $9 }' apache-access.log | sort | uniq -c | sort -nr | awk '{ print $1, $2, $3 }'
