#!/usr/bin/env bash
# This script writes its PID to /var/run/myscript.pid, handles signals, and runs indefinitely
# shellcheck disable=SC2064

PID_FILE="/var/run/myscript.pid"
echo $$ > "$PID_FILE"

trap 'echo "I hate the kill command"' SIGTERM
trap 'echo "Y U no love me?!"' SIGINT
trap 'rm -f "$PID_FILE"; exit' SIGQUIT
trap 'rm -f "$PID_FILE"; exit' SIGTERM

while true; do
  echo "To infinity and beyond"
  sleep 2
done
