#!/usr/bin/env bash
# This script displays the PID and name of processes containing "bash"
# shellcheck disable=SC2009

for pid in /proc/[0-9]*; do
  cmd=$(<"$pid/comm" 2>/dev/null)
  if [[ $cmd == *bash* ]]; then
    echo "$(basename "$pid") $cmd"
  fi
done
