#!/usr/bin/env bash
# This script stops the 4-to_infinity_and_beyond process using kill
# shellcheck disable=SC2009

pid=$(ps -eF | grep '[4]-to_infinity_and_beyond' | awk '{print $2}')
[ -n "$pid" ] && kill "$pid"
