#!/usr/bin/env bash
# This script prints "To infinity and beyond" forever and prints "I am invincible!!!" when receiving SIGTERM
# shellcheck disable=SC2064

trap 'echo "I am invincible!!!"' SIGTERM

while true; do
  echo "To infinity and beyond"
  sleep 2
done
